import { log } from "../../modules/logger.js";
var facts = [
  "The Fugaku supercomputer is the world’s fastest computer",
  "Google uses 1,000 computers in 0.2 seconds",
  "The first-ever computer had a weight of over 27 Tons",
  "The QWERTY keyboard was created to let people type more quickly.",
  "The first mouse was made from wood!",
  "Every day, about 317 million new computer viruses are discovered.",
  "Before we had Windows, it was supposed to be named Interface Manager.",
  "The first 1-gigabyte hard drive weighed as much as a refrigerator.",
  "Firefox is not a fox!",
  "Artificial intelligence may one day allow computers to understand what dogs are thinking.",
  "The first webcam was used to monitor a coffee maker, allowing users to save returns to an empty pot.",
  "The father of computer science is Alan Turning.",
  "To communicate and run a program, the first computers could only comprehend 0s and 1s.",
  "Microsoft’s founder, the infamous Bill Gates, was actually a college dropout.",
  "The original Google Storage was made up of ten 4 GB hard drives that were cased in Legos and totaled 40GB.",
  "The term “bug” became ubiquitous in computer technology after a moth triggered the Mark II computer to malfunction.",
  "Since 2005, no human has defeated a high-powered computer in a tournament standard chess match.",
  "ILOVEYOU is widely believed to be the most deadly worm virus ever developed.",
  "Intel’s 1 KB RAM memory chip was the biggest memory chip available in 1969.",
  "On average, a human blinks 20 times per minute, but using a computer reduces it to 7.",
  "The first-ever microprocessor, 4004, was designed for calculators",
  "In 1990, the first search engine was invented by Allan Emtage, who named it “Archie Query Form,” from the word “archive.”",
  "The most common password for a computer and social media platforms is 123456.",
  "There are eight varieties of computers: mainframe, supercomputer, workstation, personal computer, Apple Macintosh, laptop, tablet, and smartphone.",
  "On a keyboard, most people do not use the Scroll Lock key as they deem it useless.",
  "Linux leads the industry as it is used by Google, Facebook, Twitter, and Amazon.",
  "Researchers from the University of Manchester produced the first computer software in 1948.",
  "NASA computers were hijacked by a 15-year-old, resulting in a 21-day halt.",
  "In 1936, Russians developed a computer that functioned on water.",
  "Only two of the top 500 supercomputers are Windows-based, whereas 485 use Linux.",
  "You may heat a room with Gaming PCs more effectively than a heater.",
  "Hard drives are very sensitive to vibration, and even yelling at them or tapping the device causes them to slow down.",
  "MyDoom was the world’s fastest-spreading Virus.",
  "When you open the casing of the first Macintosh, you will find 47 autographs from members of Apple’s Macintosh division in 1982.",
  "The earliest computer was an abacus, a counting device made of thread and beads that were invented in Babylon in 500 BC.",
  "E-mail was first launched before the Internet.",
  "Physical money accounts for just around 10% of global cash, while the rest is stored on computers.",
  "Because Steve Wozniak loved repeating numerals and found them more convenient to enter, Apple’s first computer, the Apple I, was sold in 1976 for $666.66.",
  "Completely Automated Public Turing Test to Tell Computers and Humans Apart is what CAPTCHA stands for.",
  "In 1833, Charles Babbage devised all of the components that make up a modern computer.",
  "The IBM 1311, which only had a 5-megabyte capacity and looked like a washing machine, was the first disk drive to employ removable media.",
  "YouTube actually started as a dating website.",
  "Google originated from the mathematics phrase “googol,” which denotes “one followed by 100 zeros.”",
  "Since August 1998, Google’s workforce of designers and artists has created over 2000 doodles for the company’s homepage dedicated to significant events.",
  "An automated system developed at MIT can recognize the difference between happy and faked smiles.",
  "Mosaic was the original browser, released in 1993 way before the mainstream ones such as Mozilla or Chrome Explore.",
  "Summit, the world’s second-fastest computer, scored 148,600 TFLOPs.",
  "Per year, Google receives 1.2 trillion search requests, which translates to about 40,000 every second and 3.5 billion each day.",
  "The Internet was created in the 1960s with the primary aim of sharing resources.",
  "Before they could progress as staple brands, Microsoft, HP, and Apple began manufacturing computers in their garages.",
  "Sony unlawfully implanted rootkits on 22 million computers in 2005 to prevent users from stealing copyrighted music, which was difficult to eradicate.",
  "With over 746 million active users, China boasts the world’s largest internet population.",
  "Statista revealed that in 2021, there are already 15 billion mobile devices that people actively use.",
  "The worldwide retail Artificial Intelligence industry is expected to reach $110 billion by 2024, according to International Data Corporation (IDC).",
  "The overall global storage is projected to reach 175 zettabytes by the end of 2025.",
  "Deep Blue, an IBM supercomputer 1997, defeated the world-renowned chess master Garry Kasparov through a critical move that came from an unexpected bug in the software.",
  "A single computer program detects over half of all Wikipedia vandalism with more than 90% precision."
]
export async function run(client, message, args) {
  const randomElement = facts[Math.floor(Math.random() * facts.length)];
  await message.reply(randomElement) && message.react("✅");
  log(`${message.author.tag}'s got sent a computer fact (${randomElement})! `, "cmd");
}

export const name = "computerfact";